// config/monsters.ts
import { Monster, Position } from './types';

export const monsters: Monster[] = [
  {
    shortName: 'abhuman',
    category: 'regular',
    name: 'Abhuman',
    description: 'Mutated humanoid with brute strength.',
    image: '../../assets/images/abhuman.png',
    position: { row: 0, col: 0 },
    active: true,
    hp: 50,
    maxHP: 50,
    attack: 8,
    ac: 12,
    moveRate: 1,
    spawnRate: 0.2,
    spawnChance: 0.5,
    maxInstances: 10,
    soulKey: 'str:16,dex:10,con:14,int:8,wis:8,cha:6',
  },
  {
    shortName: 'night_hound',
    category: 'regular',
    name: 'Night Hound',
    description: 'Swift, feral beast that hunts in packs.',
    image: '../../assets/images/night_hound.png',
    position: { row: 0, col: 0 },
    active: true,
    hp: 30,
    maxHP: 30,
    attack: 6,
    ac: 14,
    moveRate: 2,
    spawnRate: 0.3,
    spawnChance: 0.6,
    maxInstances: 15,
    soulKey: 'str:12,dex:16,con:12,int:6,wis:10,cha:8',
  },
  {
    shortName: 'watcher_se',
    category: 'greatPower',
    name: 'Watcher of the South East',
    description: 'An ancient guardian with mystical powers.',
    image: '../../assets/images/watcher_se.png',
    position: { row: 0, col: 0 },
    active: true,
    hp: 150,
    maxHP: 150,
    attack: 15,
    ac: 16,
    moveRate: 1,
    spawnRate: 0.05,
    spawnChance: 0.2,
    maxInstances: 1,
    soulKey: 'str:18,dex:12,con:16,int:14,wis:14,cha:12',
  },
  {
    shortName: 'king_kong',
    category: 'boss',
    name: 'King Kong',
    description: 'A colossal beast of unparalleled strength.',
    image: '../../assets/images/king_kong.png',
    position: { row: 0, col: 0 },
    active: true,
    hp: 300,
    maxHP: 300,
    attack: 20,
    ac: 18,
    moveRate: 1,
    soulKey: 'str:20,dex:10,con:18,int:8,wis:10,cha:14',
  },
];